spring:
  application:
    name: reward-manager
  profiles:
    active:
db:
  host: ec2-54-75-246-118.eu-west-1.compute.amazonaws.com
  port: 5432
  database: d1i8vbp3avpj99
  username: ymzthsnuwgqdfi
  password: 733301615685bdabaecce7ab8a2fe420d367df9e53b2d913941e3007fada9e86